/** Boredom activity catalogue — every entry has validated metadata tags. */

/** @type {import('./types.js').Activity[]} */
export const BOREDOM_ACTIVITIES = [
  // ── Home · solo · very low · free · comfort/switch-off ──
  {
    id: 'home-tea-ritual',
    title: 'Five-minute tea or snack ritual',
    description: 'Make a drink or snack and sit without your phone for five minutes.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'switch-off'],
    durations: ['five-minutes'],
    costs: ['free'],
  },
  {
    id: 'home-comfort-watch',
    title: 'Comfort watch — one episode',
    description: 'Twenty minutes of something you already love. Blanket encouraged.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'switch-off'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-gentle-stretch',
    title: 'Gentle stretch by the window',
    description: 'Slow stretches for five to ten minutes. No workout pressure.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'movement'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-doodle',
    title: 'Five-minute doodle',
    description: 'Timer on. Draw shapes or patterns with no judging.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['creativity', 'comfort'],
    durations: ['five-minutes'],
    costs: ['free'],
  },
  {
    id: 'home-nap-zone',
    title: 'Create a cosy nest and rest',
    description: 'Blankets, dim lights, eyes closed for fifteen minutes.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['very-low'],
    cravings: ['comfort', 'switch-off'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-game-round',
    title: 'One quick game round',
    description: 'A single round of a phone or card game. Stop when it ends.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['mental', 'comfort'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-read-chapter',
    title: 'Read one chapter',
    description: 'One chapter only — then decide if you want more.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm', 'very-low'],
    cravings: ['switch-off', 'mental'],
    durations: ['one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-rearrange-corner',
    title: 'Refresh one small corner',
    description: 'Rearrange a shelf or surface. Add one thing that makes you smile.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['creativity', 'comfort'],
    durations: ['one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-cook-simple',
    title: 'Try a simple new recipe',
    description: 'Five ingredients or fewer. Imperfect is fine.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['calm', 'movement'],
    cravings: ['creativity', 'comfort'],
    durations: ['one-hour'],
    costs: ['small-spend'],
  },
  {
    id: 'home-cook-together',
    title: 'Cook something together',
    description: 'Pick a simple recipe and make it with someone. Mess allowed.',
    settings: ['home'],
    socialModes: ['with-someone'],
    energy: ['calm', 'movement'],
    cravings: ['creativity', 'connection'],
    durations: ['one-hour', 'few-hours'],
    costs: ['small-spend'],
  },
  {
    id: 'home-dance-break',
    title: 'Three-song dance break',
    description: 'Put on three songs and move however you like.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['movement', 'high'],
    cravings: ['movement', 'novelty'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'home-craft-hour',
    title: 'One-hour craft project',
    description: 'Finish something small — a card, repot a plant, organise a drawer.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['creativity'],
    durations: ['one-hour', 'few-hours'],
    costs: ['small-spend'],
  },
  {
    id: 'home-playlist',
    title: 'Build a mood playlist',
    description: 'Songs for how you want to feel, not how you feel now.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['creativity', 'comfort'],
    durations: ['one-hour'],
    costs: ['free'],
  },

  // ── Home · paid experiences ──
  {
    id: 'home-film-rental',
    title: 'Rent or buy a film at home',
    description: 'Pick something you have been meaning to watch — make it an event with snacks.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['calm', 'very-low'],
    cravings: ['comfort', 'switch-off', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },
  {
    id: 'home-delivery-treat',
    title: 'Order a nicer takeaway or dessert',
    description: 'Treat yourself to something a step above the usual — no cooking required.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'novelty'],
    durations: ['one-hour'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'home-game-purchase',
    title: 'Buy a small game or expansion',
    description: 'Digital or physical — something playful you can start tonight.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['calm', 'high'],
    cravings: ['mental', 'novelty', 'comfort'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },
  {
    id: 'home-craft-supplies',
    title: 'Buy supplies for a home project',
    description: 'Pick up or order materials for something creative you can start today.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['calm'],
    cravings: ['creativity', 'comfort'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'home-spa-kit',
    title: 'Buy a bath or self-care kit',
    description: 'Face mask, bath bomb, nice soap — a small splurge for comfort at home.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'switch-off'],
    durations: ['one-hour'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'home-book-audio',
    title: 'Buy a book or audiobook',
    description: 'Choose something you are curious about and settle in to start it.',
    settings: ['home'],
    socialModes: ['solo'],
    energy: ['calm', 'very-low'],
    cravings: ['mental', 'comfort', 'switch-off'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'home-cook-class-kit',
    title: 'Try a meal-kit or baking box',
    description: 'Order a kit with everything included — cooking as an activity, not a chore.',
    settings: ['home'],
    socialModes: ['solo', 'with-someone'],
    energy: ['calm', 'movement'],
    cravings: ['creativity', 'comfort', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },

  // ── Out · solo · movement · free ──
  {
    id: 'out-photo-walk',
    title: 'Themed photo walk',
    description: 'Pick a theme and photograph five examples on a walk.',
    settings: ['out'],
    socialModes: ['solo'],
    energy: ['movement', 'high'],
    cravings: ['exploration', 'creativity', 'novelty'],
    durations: ['one-hour'],
    costs: ['free'],
  },
  {
    id: 'out-podcast-walk',
    title: 'New route with a podcast',
    description: 'Walk a street you have never taken with one episode.',
    settings: ['out'],
    socialModes: ['solo'],
    energy: ['movement', 'calm'],
    cravings: ['exploration', 'switch-off'],
    durations: ['one-hour'],
    costs: ['free'],
  },
  {
    id: 'out-tiny-adventure',
    title: 'Five-minute tiny adventure',
    description: 'Walk to the end of the street and back a different way.',
    settings: ['out'],
    socialModes: ['solo'],
    energy: ['movement'],
    cravings: ['exploration', 'novelty'],
    durations: ['five-minutes'],
    costs: ['free'],
  },
  {
    id: 'out-nature-sit',
    title: 'Ten minutes in nature',
    description: 'Sit in a park or garden. No phone. Just notice.',
    settings: ['out'],
    socialModes: ['solo'],
    energy: ['very-low', 'calm'],
    cravings: ['comfort', 'switch-off'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'out-sunset',
    title: 'Sunset or sky watch',
    description: 'Find a spot and watch the sky change.',
    settings: ['out'],
    socialModes: ['solo'],
    energy: ['calm'],
    cravings: ['comfort', 'exploration'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },

  // ── Out · ambient · calm · small spend ──
  {
    id: 'out-solo-cafe',
    title: 'Solo café visit',
    description: 'A drink somewhere cosy. People-watching optional.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['comfort', 'switch-off'],
    durations: ['one-hour'],
    costs: ['small-spend'],
  },
  {
    id: 'out-library',
    title: 'Browse the library',
    description: 'Wander shelves, read in a corner, people-watch quietly.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['calm', 'very-low'],
    cravings: ['mental', 'exploration', 'switch-off'],
    durations: ['one-hour', 'few-hours'],
    costs: ['free'],
  },
  {
    id: 'out-bookshop',
    title: 'Browse a bookshop',
    description: 'Wander without a purchase plan. Optional small treat.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['mental', 'exploration'],
    durations: ['one-hour'],
    costs: ['free', 'small-spend'],
  },
  {
    id: 'out-gallery',
    title: 'Visit a gallery or exhibition',
    description: 'Wander at your own pace. Leave when you have had enough.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['mental', 'exploration', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'out-museum',
    title: 'Museum or attraction visit',
    description: 'Explore one section that catches your eye.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat', 'with-someone'],
    energy: ['calm', 'movement'],
    cravings: ['exploration', 'mental', 'novelty'],
    durations: ['few-hours', 'one-hour'],
    costs: ['higher-spend'],
  },

  // ── Out · with someone · paid ──
  {
    id: 'out-cinema',
    title: 'See a film at the cinema',
    description: 'Pick something fun — no need for it to be important.',
    settings: ['out'],
    socialModes: ['with-someone', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['comfort', 'novelty', 'switch-off'],
    durations: ['few-hours', 'one-hour'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-bowling',
    title: 'Go bowling or mini-golf',
    description: 'Playful hour that gets you moving without a big commitment.',
    settings: ['out'],
    socialModes: ['with-someone'],
    energy: ['movement', 'high'],
    cravings: ['movement', 'connection', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-escape-room',
    title: 'Try an escape room or puzzle experience',
    description: 'A focused hour of curiosity with someone else.',
    settings: ['out'],
    socialModes: ['with-someone'],
    energy: ['high', 'movement'],
    cravings: ['mental', 'exploration', 'connection'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-skating',
    title: 'Try skating or a movement class',
    description: 'Book a beginner session — roller skating, climbing taster or similar.',
    settings: ['out'],
    socialModes: ['with-someone', 'solo'],
    energy: ['movement', 'high'],
    cravings: ['movement', 'novelty', 'exploration'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-restaurant',
    title: 'Try a new restaurant or food spot',
    description: 'Share a meal somewhere neither of you has been.',
    settings: ['out'],
    socialModes: ['with-someone'],
    energy: ['calm', 'movement'],
    cravings: ['exploration', 'connection', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'out-cafe-new',
    title: 'Visit a new café or bakery',
    description: 'Try somewhere you have noticed but never been.',
    settings: ['out'],
    socialModes: ['with-someone', 'solo', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['comfort', 'exploration', 'novelty'],
    durations: ['one-hour'],
    costs: ['small-spend', 'higher-spend'],
  },
  {
    id: 'out-workshop',
    title: 'Try a creative workshop',
    description: 'Pottery taster, printmaking, cooking class — something hands-on.',
    settings: ['out'],
    socialModes: ['with-someone', 'around-people-no-chat'],
    energy: ['calm', 'movement'],
    cravings: ['creativity', 'exploration', 'novelty'],
    durations: ['few-hours', 'one-hour'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-spa',
    title: 'Pool, spa or wellness session',
    description: 'A restorative hour — swim, sauna or similar if available.',
    settings: ['out'],
    socialModes: ['solo', 'with-someone', 'around-people-no-chat'],
    energy: ['calm', 'very-low'],
    cravings: ['comfort', 'switch-off'],
    durations: ['few-hours', 'one-hour'],
    costs: ['higher-spend'],
  },
  {
    id: 'out-local-event',
    title: 'Check out a local event',
    description: 'Look up what is on nearby — a talk, market, fair or community event.',
    settings: ['out'],
    socialModes: ['with-someone', 'around-people-no-chat', 'solo'],
    energy: ['movement', 'high'],
    cravings: ['exploration', 'novelty'],
    durations: ['few-hours', 'one-hour'],
    costs: ['higher-spend', 'free'],
  },
  {
    id: 'out-hire-bike',
    title: 'Hire a bike or scooter for an hour',
    description: 'Explore a route you do not usually take.',
    settings: ['out'],
    socialModes: ['solo', 'with-someone'],
    energy: ['movement', 'high'],
    cravings: ['movement', 'exploration', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['higher-spend', 'small-spend'],
  },
  {
    id: 'out-book-buy-read',
    title: 'Buy a book and read somewhere pleasant',
    description: 'Pick a book in a shop, then sit in a café or park to start it.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['calm'],
    cravings: ['mental', 'comfort', 'exploration'],
    durations: ['one-hour', 'few-hours'],
    costs: ['small-spend', 'higher-spend'],
  },
  {
    id: 'out-coffee-catchup',
    title: 'Coffee catch-up',
    description: 'Invite one person for a low-pressure drink nearby.',
    settings: ['out'],
    socialModes: ['with-someone'],
    energy: ['calm'],
    cravings: ['connection', 'comfort'],
    durations: ['one-hour'],
    costs: ['small-spend'],
  },
  {
    id: 'out-market-wander',
    title: 'Wander a market',
    description: 'Browse stalls with no purchase required. Optional small treat.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat', 'with-someone'],
    energy: ['movement', 'calm'],
    cravings: ['exploration', 'novelty'],
    durations: ['one-hour', 'few-hours'],
    costs: ['free', 'small-spend'],
  },
  {
    id: 'out-mystery-door',
    title: 'Step inside somewhere new',
    description: 'Enter a shop or building you have always walked past.',
    settings: ['out'],
    socialModes: ['solo', 'around-people-no-chat'],
    energy: ['movement', 'calm'],
    cravings: ['exploration', 'novelty'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },

  // ── Flexible setting ──
  {
    id: 'flex-journal',
    title: 'Five-minute journal dump',
    description: 'Write whatever is in your head for five minutes. No editing.',
    settings: ['home', 'either'],
    socialModes: ['solo', 'flexible'],
    energy: ['calm', 'very-low'],
    cravings: ['comfort', 'mental', 'switch-off'],
    durations: ['five-minutes'],
    costs: ['free'],
  },
  {
    id: 'flex-curious-video',
    title: 'Watch one curious video',
    description: 'One documentary clip, tutorial or rabbit hole — then stop.',
    settings: ['home', 'either'],
    socialModes: ['solo', 'flexible'],
    energy: ['calm'],
    cravings: ['mental', 'switch-off'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
  {
    id: 'flex-puzzle',
    title: 'Do a puzzle or brain teaser',
    description: 'Crossword, sudoku, or phone puzzle — one session only.',
    settings: ['home', 'either'],
    socialModes: ['solo', 'flexible'],
    energy: ['calm'],
    cravings: ['mental'],
    durations: ['five-minutes', 'one-hour'],
    costs: ['free'],
  },
]
